//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri May 19 18:49:57 2023 by ROOT version 6.28/00)
//      from the StreamerInfo in file /data/submit/pdmonte/D02/GJets_HT-40To100_TuneCP5_13TeV-madgraphMLM-pythia8+RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2+MINIAODSIM/200FAB84-65CB-A945-8F9F-9EB261762271.root
//////////////////////////////////////////////////////////


#ifndef edm__ProcessHistory_h
#define edm__ProcessHistory_h
namespace edm {
class ProcessHistory;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>
#include "edm__ProcessConfiguration.h"

namespace edm {
class ProcessHistory {

public:
// Nested classes declaration.

public:
// Data Members.
   vector<edm::ProcessConfiguration> data_;       //

   ProcessHistory();
   ProcessHistory(ProcessHistory && ) = default;
   ProcessHistory &operator=(const ProcessHistory & );
   ProcessHistory(const ProcessHistory & );
   virtual ~ProcessHistory();

   ClassDef(ProcessHistory,12); // Generated by MakeProject.
};
} // namespace
#endif
