//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri May 19 18:49:57 2023 by ROOT version 6.28/00)
//      from the StreamerInfo in file /data/submit/pdmonte/D02/GJets_HT-40To100_TuneCP5_13TeV-madgraphMLM-pythia8+RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2+MINIAODSIM/200FAB84-65CB-A945-8F9F-9EB261762271.root
//////////////////////////////////////////////////////////


#ifndef edm__ParameterSetBlob_h
#define edm__ParameterSetBlob_h
namespace edm {
class ParameterSetBlob;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <string>

namespace edm {
class ParameterSetBlob {

public:
// Nested classes declaration.

public:
// Data Members.
   string      pset_;       //

   ParameterSetBlob();
   ParameterSetBlob(ParameterSetBlob && ) = default;
   ParameterSetBlob &operator=(const ParameterSetBlob & );
   ParameterSetBlob(const ParameterSetBlob & );
   virtual ~ParameterSetBlob();

   ClassDef(ParameterSetBlob,11); // Generated by MakeProject.
};
} // namespace
#endif
