//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri May 19 18:49:57 2023 by ROOT version 6.28/00)
//      from the StreamerInfo in file /data/submit/pdmonte/D02/GJets_HT-40To100_TuneCP5_13TeV-madgraphMLM-pythia8+RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2+MINIAODSIM/200FAB84-65CB-A945-8F9F-9EB261762271.root
//////////////////////////////////////////////////////////


#ifndef edm__Hash_1__h
#define edm__Hash_1__h
namespace edm {
template <int T0> class Hash;
template <> class Hash<1>;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <string>

namespace edm {
template <int T0> class Hash;
template <> class Hash<1> {

public:
// Nested classes declaration.

public:
// Data Members.
   string      hash_;       //

   Hash();
   Hash(Hash && ) = default;
   Hash &operator=(const Hash & );
   Hash(const Hash & );
   virtual ~Hash();

   ClassDef(Hash,12); // Generated by MakeProject.
};
} // namespace
#endif
